package com.wsb.wsb_bugtracker.enums;

public enum AuthorityName {
    ROLE_USERS_TAB, ROLE_CREATE_USER, ROLE_DELETE_USER, ROLE_EDIT_USER,
    ROLE_ISSUES_TAB, ROLE_CREATE_ISSUE, ROLE_DELETE_ISSUE, ROLE_EDIT_ISSUE,
    ROLE_PROJECTS_TAB, ROLE_CREATE_PROJECT, ROLE_DELETE_PROJECT, ROLE_EDIT_PROJECT
}